// Generates src/engine/calibration.ts : per-asset systematic scale and idiosyncratic vol so realised vol ~= target.
import { writeFileSync } from 'node:fs';
import { Rng } from '../src/engine/rng';
import { createMarket, stepMarket } from '../src/engine/marketEngine';
import { DIFFICULTY } from '../src/engine/difficulty';
import { CATALOG } from '../src/engine/catalog';
import { marketHours, tOf, DAY } from '../src/engine/time';

function measure(mode: 'sys' | 'full', calib: Record<string, { sys: number; idio: number }>): Record<string, number> {
  const acc: Record<string, number[]> = {};
  for (const seed of [1, 2, 3, 4, 5]) {
    const rng = new Rng(seed * 101); const diff = DIFFICULTY.NORMAL; const m: any = createMarket(rng, diff, -70);
    for (const d of CATALOG) { const c = calib[d.id]; if (!c) continue; m.assets[d.id].idioVol = mode === 'sys' ? 1e-9 : c.idio; }
    (m as any).__sysScale = Object.fromEntries(Object.entries(calib).map(([k, v]) => [k, v.sys]));
    let t = tOf(-70); const dt = 60; const last: Record<string, number> = {};
    for (let i = 0; i < 70 * DAY / dt; i++) {
      t += dt; stepMarket(m, { t, dt, rng, diff, mh: marketHours(t), sentiment: 0, warm: true });
      if (i % (DAY / dt) === 0) for (const d of CATALOG) { if (d.cls === 'index') continue; const p = m.assets[d.id].price; if (last[d.id]) (acc[d.id] ??= []).push(Math.log(p / last[d.id])); last[d.id] = p; }
    }
  }
  const out: Record<string, number> = {};
  for (const id of Object.keys(acc)) { const r = acc[id]; const mean = r.reduce((a, b) => a + b, 0) / r.length; out[id] = Math.sqrt(r.reduce((a, b) => a + (b - mean) ** 2, 0) / (r.length - 1)); }
  return out;
}

let calib: Record<string, { sys: number; idio: number }> = {};
for (const d of CATALOG) if (d.cls !== 'index') calib[d.id] = { sys: 1, idio: 0 };
for (let iter = 0; iter < 3; iter++) {
  const sysOnly = measure('sys', calib);
  for (const d of CATALOG) {
    if (d.cls === 'index') continue;
    const s = sysOnly[d.id];
    const target = d.dailyVol;
    // cap systematic share at 80% of target variance; scale down if it exceeds
    const maxSys = target * 0.82;
    const c = calib[d.id];
    const curSys = s / c.sys;           // sys-only sd at scale 1
    c.sys = curSys > maxSys ? maxSys / curSys : 1;
    const sysFinal = curSys * c.sys;
    c.idio = Math.sqrt(Math.max(target * target - sysFinal * sysFinal, (target * 0.35) ** 2));
  }
  const full = measure('full', calib);
  const worst = Object.entries(full).map(([id, sd]) => [id, sd / CATALOG.find((x) => x.id === id)!.dailyVol] as const).sort((a, b) => Math.abs(b[1] - 1) - Math.abs(a[1] - 1)).slice(0, 3);
  console.log('iter', iter, 'worst ratios', worst.map(([i, r]) => i + ':' + r.toFixed(2)).join('  '));
  // fine-tune idio so the full model lands on target
  for (const d of CATALOG) {
    if (d.cls === 'index') continue;
    const r = full[d.id] / d.dailyVol;
    if (isFinite(r) && r > 0) calib[d.id].idio = Math.max(d.dailyVol * 0.15, calib[d.id].idio / Math.pow(r, 1.3));
  }
}
const lines = Object.entries(calib).map(([id, c]) => `  '${id}': { sys: ${c.sys.toFixed(4)}, idio: ${c.idio.toFixed(6)} },`).join('\n');
writeFileSync('src/engine/calibration.ts', `// AUTO-GENERATED by scripts/gencalib.ts - do not edit by hand.\nexport const CALIB: Record<string, { sys: number; idio: number }> = {\n${lines}\n};\n`);
console.log('written', Object.keys(calib).length);
